### ISSUE TITLE
Tasks are seen in the pull-down list, but only "no due tasks" was shown on the status bar

### ISSUE THREAD

**Issue by JunCEEE** [tarelda/todoist-indicator#8] opened 2023-05-04 08:29 UTC
Tasks were seen in the pull-down list, but only "no due tasks" was shown on the status bar. 
**Even though the due times for those tasks were already set.**

![image](https://user-images.githubusercontent.com/3163505/236150163-dcab3a8e-4fc7-45aa-b9ee-9b1d20d7cb47.png)

**Comment by tarelda** [comment] 2023-05-04 09:26
Isn't this duplicate of #4 ?

**Comment by JunCEEE** [comment] 2023-05-04 11:18
Thanks for your prompt reply. I'm afraid that the counter is just not working.

I have my task list like this, with two tasks that are past their due time:
![image](https://user-images.githubusercontent.com/3163505/236188075-a63902d0-f403-4be7-8a75-25a20ddf819e.png)

However, it's still showing "no due tasks" on the task bar.

Actually, would it be a good idea to add an option to show the top task name? I feel it would be then more useful to me, and I'd be happy to help with developing that.

**Comment by JunCEEE** [comment] 2023-05-05 07:25
I might have understood what happened. The tasks that are past their due time **today** are not sorted as "Overdue" tasks immediately, but kept in the "Today" category. Therefore, the tasks that are overdue  **today** are not counted, while the counter is counting only the tasks in the "Overdue" category.

Thank you very much for developing this convenient tool. Please feel free to close this issue whenever you like.

**Closed as completed** 2023-05-15 12:08 UTC
