### ISSUE TITLE
Can't open settings menu

### ISSUE THREAD

**Issue by alizehctl** [tarelda/todoist-indicator#2] opened 2021-10-15 08:52 UTC
I'm using Fedora 34, with GNOME 40.4

I get this error when I try to open the extension settings:
```
TypeError: this.add is not a function
```

Stack trace:
```
_init@/home/aadil/.local/share/gnome-shell/extensions/todoist@tarelda.github.com/prefs.js:27:10
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
buildPrefsWidget@/home/aadil/.local/share/gnome-shell/extensions/todoist@tarelda.github.com/prefs.js:81:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

![image](https://user-images.githubusercontent.com/31581044/137460427-62557c3a-6aff-4e6b-bb9b-938eaf072587.png)

**Comment by tarelda** [comment] 2021-10-18 18:30
Duplicate of #3

**Closed as completed by tarelda** 2021-10-18 18:30 UTC
